### ISSUE TITLE
How to document methods and method arguments?

### ISSUE THREAD

**Issue by cetinsert** [open-wc/api-viewer-element#47]
Is there a way to document methods and their arguments in a consistent fashion?

**Comment by web-padawan** [comment]
Thanks for the issue. This needs https://github.com/runem/web-component-analyzer/issues/146 to be implemented.

**Comment by cetinsert** [comment]
Actually, in my workflow, I manually edit the `custom-elements.json` file, completely by passing the need for the analyzer.

**Comment by web-padawan** [comment]
Depends on #61

**Comment by Dav1dde** [comment]
#61 seems to be done, has there been any progress on it? It seems like 1.0.0-pre.3 does not display methods.

**Comment by web-padawan** [comment]
Yes the support for methods isn't added yet. I will work on this when I have time, hopefully this Friday.

**Comment by rpsirois** [comment]
@web-padawan thanks for taking care of this issue. I noticed there was no information in the changelog and the CDNs are still at
- unpkg: 1.0.0-pre.3
- skypack: 1.0.0-pre.3
- jspm: 1.0.0-pre.2
Is there a targeted version for this release or do I need to build from source? Thank you for your work on this library.
